### ISSUE TITLE
About using DDIM sampling

### ISSUE THREAD

**Issue by Suimingzhe** [ericl122333/PatchDiffusion-Pytorch#2]
Thanks for your work. I tried to generate images on FFHQ and the quality seems pretty good.

I find the sampling process is performed under "p_sample_loop" by default, and does it support ddim sampling or even further DPM-Solver/DPM-Solver++? I want to speed up the sampling time further.

Look forward to your reply.

**Comment by ericl122333** [comment]
Hi Suimingzhe,

We do support using DDIM sampling (by specifying use_ddim as an argument to the image_sample.py script. In general, DDIM sampling works pretty well in as little as 10-20 steps, less than this and it'll start to produce blurry samples (feel free to try out yourself, and see if it gives acceptable sample quality at your desired speed).  

Unfortunately we currently do not support DPM-solver since we wrote this codebase before we were aware of the paper; we may implement it in the future. For the moment, if you want to try out DPM-solver , you could use huggingface's diffusers (https://huggingface.co/docs/diffusers/api/schedulers#diffusers.DPMSolverMultistepScheduler). I'm not too familiar with the library, but you should be able to just import their scheduler, passing in "model_output" from our model as the argument to DPMSolverMultistepScheduler.step (make sure you pass in prediction_type = "sample" to the config, since we use x-prediciton). You will probably have to modify the Gaussian_diffusion.py file to add this sampler.  But one nice thing about diffusers is it supports many samplers (e.g. PNDM, Karras, etc.) so you can choose what works fastest/best.  

Hope this helps,
Eric

**Comment by Suimingzhe** [comment]
Thanks for your prompt and detailed reply！！

I tried to generate 16 images on one GPU with ddim sampling in 20 steps just now, and it finished sampling process in 10s. I think it is enough for me. I will also try to use DPM-solver as you said. Thanks again.
