### ISSUE TITLE
Training on low resolutions

### ISSUE THREAD

**Issue by ariel415el** [ericl122333/PatchDiffusion-Pytorch#3]
Hi, 

Thanks for this very interesting work.
I was wondering whether you tried training on lower resolutions datasets like FFHQ-128, Celeb-A-64 or Mnist?
It seems to me that it might still be relevant to train your model with 2x2 and 4x4 patches on such datasets.

Do you expect your model to work on such scenarios? what do you expect the training speed boost to be here?
Will the training converge faster compared to pixel diffusion?

**Comment by ericl122333** [comment]
Hi ariel415el,

We're glad you're interested in this work. Our experiments considered only high-resolution datasets (res>=256) since that's where we'd see the greatest efficiency improvement. For lower resolution datasets one GPU is often sufficient if it's small scale. That being said, you could definitely apply the patching method to these problems. Depending on your config & patch size, it could be a pretty substantial speed boost, especially if using a larger batchsize allowed by the low memory of patched diffusion model. However, there might be a performance degradation if resolution/patch_size is too small, so if possible maybe keep resolution after patching >=32. 

Hope this helps,
Eric
